version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  db:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: